# Generated by Django 2.2.28 on 2023-02-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.TextField()),
                ('courseId', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
